### PR TITLE
Create dotnet new template

### PR DESCRIPTION
**Pull request by mvsmal**
Since the current extension creates a project template only in Visual Studio, users of other IDEs are not able to use it. This PR adds a Nuget package which is a template for `dotnet new` template engine.
It allows to use the template from command line as well as to install it in JetBrains Rider.

The `.csproj` file will be created in the new format but still using .NET Framework 4.6.1. This will allow easier migration to .NET Core (Standard). Actually we can user .NET Standard 2.0 already now, since .NET 4.6.1 supports it.

My only concern is versions of dependencies, especially `VirtoCommerce.Platform.Core`. Which versions should we use in this template?

### CODE REVIEW

**Review by tatarincev — COMMENTED** [review]
Could we avoid of duplication and use the already existing templates?
UPD:
I think there aren't any way to use latest `VirtoCommerce.Platform.Core` version, so we should set this version manually each time

**Comment by mvsmal** [comment]
There is a bit different mechanism of string replacement. I will check what's possible. Shall I stick to the new format of `.csproj` file?

**Comment by tatarincev** [comment]
I don't think it is necessary now.

**Comment by mvsmal** [comment]
Certainly, it's not necessary, although I'm already touching it 😃

**Comment by mvsmal** [comment]
It is possible to use the same template files, however we would need to copy them to a specific folder before packing. Also it will complicate the development a bit.

**Comment by tatarincev** [comment]
@mvsmal The guys from client projects have another solution for quickly creating modules from a template. It based on powershell script and templates and absolutely independent from IDE. Please ask @artem-dudarev for more details if you want to continue develop this topic further

**Comment by artem-dudarev** [comment]
[vc-module-template.zip](https://github.com/VirtoCommerce/vc-visualstudio-templates/files/2629422/vc-module-template.zip)
Instructions are in the readme.md file.
Basically all you have to do is to edit constants in the beggining of the Module_Template.ps1 and run it.

**Comment by mvsmal** [comment]
@artem-dudarev Thanks a lot! That's a better version. Although it also has points for improvements, for example we can use script parameters to avoid manual replacement of constants. Anyways, thank you. Since there are not that many many people using smth different than Visual Studio, we can reject this PR and forget about `dotnet new` for a while.

**Pull request closed without merging**
